name: Lighthouse Monitoring

on:
  schedule:
    - cron: '0 6 * * *'  # каждый день в 06:00 UTC
  workflow_dispatch:     # возможность запускать вручную

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://ramadanovosibirsk.com/
            https://ramadanovosibirsk.com/loyalty/
            https://ramadanovosibirsk.com/apartments/
          uploadArtifacts: true
          temporaryPublicStorage: true
